/*_JCH_coffess_test.html_text/coffeescript */
// Generated by CoffeeScript 1.6.3
console.log("hello world!");

console.log("hello wangyu1!");
/*_JCH_*/
/*_JCH_coffess_test.html_text/coffeescript_0 */
// Generated by CoffeeScript 1.6.3
console.log("hello world!");

console.log("hello wangyu0!");

console.log("xxxxooo");
/*_JCH_*/
